---
wildfly_enable_yml_config: True
wildfly_config_base: 'standalone-ha.xml'
wildfly_yml_configs:
    - yaml_configuration.yml.j2
wildfly_validation_queries:
    - { query: ':read-attribute(name=product-version)', expected_result:  '31.0.0.Final', expected_result_undefined: false}
    - { query: '/socket-binding-group=standard-sockets/socket-binding=http:read-attribute(name=port, resolve-expressions=true)', expected_result:  '8080', expected_result_undefined: false}

