/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java21;

public class App {
    public void startThread() {
        Runnable runnable = () -> {
            for(int i=0; i<10; i++) {
                System.out.println("Index: " + i);
            }
        };
        
        Thread vThread = Thread.ofVirtual().start(runnable);
    }

    public static void main(String[] args) {
        new App().startThread();
    }
}
